samples: "samples.tsv"
units: "units.tsv"

sortmerna:
  fasta:
    - "reference/23s.fasta"
  index: "reference/idx"

tools:
  common: "docker://marrip/common:1.1.1"
  sortmerna: "docker://marrip/sortmerna:4.3.4"
